name: Deploy site

on:
  push:
    branches: ["main"]

  workflow_dispatch:

  repository_dispatch:
    types: [aep-spec-update]

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Print event info
        run: echo "Received repository dispatch event from repo-aep!"

      - name: Verify specs include latest updates
        run: |
          find src/content/aeps/ -type f | xargs -I@ sh -c "set -x; grep -n ^ '@'; set +x" || true
