name: Deploy site

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - name: Print event info
        run: echo "Received repository dispatch event from repo-aep!"
